version: '3.8'

volumes:
    dbVolume: {}
    wpVolume: {}

networks:
    mynet:
        name:   mynet
        driver: bridge

services:
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        restart: always
        volumes:
            - dbVolume:/var/lib/mysql
        expose:
            - "3306"
        env_file:
            - .env
        networks:
            - mynet
        tty: true

    wordpress:
        container_name: wordpress
        depends_on:
            - mariadb
        build: ./requirements/wordpress
        restart: always
        volumes:
            - wpVolume:/var/www/html
        expose:
            - "9000"
        env_file:
            - .env
        networks:
            - mynet
        tty: true

    nginx:
        container_name: nginx
        build: ./requirements/nginx
        depends_on:
            - wordpress
        restart: always
        ports:
            - "443:443"
        volumes:
            - wpVolume:/var/www/html
        networks:
            - mynet
        tty: true

# https://github.com/alexnik42/inception
